### PR TITLE
Update npm-publish.yml

### PR DESCRIPTION
**Pull request by ImAvinashSharma**
Added GITHUB_TOKEN

### CODE REVIEW

**Comment by adarshaacharya** [comment]
Hi @ImAvinashSharma  thanks for taking interest in project. Any specific reason why should we add github token?

**Comment by ImAvinashSharma** [comment]
Hey, there the GitHub `GITHUB_TOKEN` environment variable allows you to have different env for different node/.npmrc or any other environments.
It prevents having conflicts in your repo 🚀 .

**Comment by adarshaacharya** [comment]
That's good ! But do we actually need it on `npm publish` may be we can add this on `npm build` or test workflow.

**Comment by ImAvinashSharma** [comment]
```But do we actually need it on npm publish maybe we can add this on npm build or test workflow?``` @adarshaacharya You are putting on GitHub know. I read is somewhere that it is important to add 😃  🚀

**Pull request merged**
